# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-16 13:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20151216_1305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='polynomial',
            name='poynomial',
        ),
        migrations.AddField(
            model_name='polynomial',
            name='polynomial',
            field=models.CharField(default=datetime.datetime(2015, 12, 16, 13, 6, 16, 106745, tzinfo=utc), max_length=500),
            preserve_default=False,
        ),
    ]
