# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-16 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20151216_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polynomial',
            name='polynomial',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
