# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-10 22:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coauthor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coauthor', models.CharField(max_length=30)),
                ('institution', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doi', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=30)),
                ('publish_date', models.DateTimeField(verbose_name='date published')),
                ('coauthors', models.ManyToManyField(to='research.Coauthor')),
            ],
        ),
    ]
