# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-10 23:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0002_auto_20151210_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='doi',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='publish_date',
            field=models.DateField(blank=True, null=True, verbose_name='date published'),
        ),
    ]
