# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-10 23:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0003_auto_20151210_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='coauthors',
            field=models.ManyToManyField(blank=True, null=True, to='research.Coauthor'),
        ),
    ]
